// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/subbu/family_tree/client/google"
	"github.com/subbu/family_tree/config"
	"github.com/subbu/family_tree/handlers"
	"github.com/subbu/family_tree/handlers/admin"
	"github.com/subbu/family_tree/handlers/auth"
	family2 "github.com/subbu/family_tree/handlers/family"
	gedcom2 "github.com/subbu/family_tree/handlers/gedcom"
	"github.com/subbu/family_tree/handlers/health"
	invite2 "github.com/subbu/family_tree/handlers/invite"
	person2 "github.com/subbu/family_tree/handlers/person"
	photo2 "github.com/subbu/family_tree/handlers/photo"
	relationship2 "github.com/subbu/family_tree/handlers/relationship"
	search2 "github.com/subbu/family_tree/handlers/search"
	"github.com/subbu/family_tree/handlers/tree"
	"github.com/subbu/family_tree/server"
	"github.com/subbu/family_tree/services/family"
	"github.com/subbu/family_tree/services/gedcom"
	"github.com/subbu/family_tree/services/invite"
	"github.com/subbu/family_tree/services/person"
	"github.com/subbu/family_tree/services/photo"
	"github.com/subbu/family_tree/services/relationship"
	"github.com/subbu/family_tree/services/search"
	"github.com/subbu/family_tree/services/user"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	client, err := providePostgresClient(configConfig)
	if err != nil {
		return nil, err
	}
	googleClient := provideGoogleClient(configConfig)
	service := user.NewService(client)
	authService := provideAuthService(googleClient, client, service, configConfig)
	handler := auth.NewHandler(authService, configConfig)
	familyService := family.NewService(client)
	inviteService := invite.NewService(client)
	familyHandler := family2.NewHandler(familyService, inviteService)
	inviteHandler := invite2.NewHandler(inviteService, familyService)
	personService := person.NewService(client)
	relationshipService := relationship.NewService(client)
	personHandler := person2.NewHandler(personService, familyService, relationshipService)
	relationshipHandler := relationship2.NewHandler(relationshipService, familyService, personService)
	searchService := search.NewService(client)
	searchHandler := search2.NewHandler(searchService, familyService)
	storageClient, err := provideStorageClient(configConfig)
	if err != nil {
		return nil, err
	}
	photoService := photo.NewService(client, storageClient)
	photoHandler := photo2.NewHandler(photoService, familyService)
	treeHandler := tree.NewHandler(personService, relationshipService, familyService)
	gedcomService := gedcom.NewService(client)
	gedcomHandler := gedcom2.NewHandler(gedcomService, familyService)
	adminHandler := admin.NewHandler(service, familyService)
	healthHandler := health.NewHandler(client)
	dependencies := handlers.Dependencies{
		Auth:         handler,
		Family:       familyHandler,
		Invite:       inviteHandler,
		Person:       personHandler,
		Relationship: relationshipHandler,
		Search:       searchHandler,
		Photo:        photoHandler,
		Tree:         treeHandler,
		Gedcom:       gedcomHandler,
		Admin:        adminHandler,
		Health:       healthHandler,
		AuthSvc:      authService,
	}
	router := handlers.NewRouter(dependencies)
	serverServer := server.New(configConfig, client, router)
	return serverServer, nil
}

// wire.go:

func provideGoogleClient(cfg config.Config) google.Client {
	redirectURL := cfg.FrontendURL + "/api/auth/google/callback"
	return google.New(cfg.GoogleClientID, cfg.GoogleClientSecret, redirectURL)
}
